apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: prog3360-assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      version: v1
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
        - name: product-api
          image: product-service:v1
          ports:
            - containerPort: 8081