apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prog3360-assignment
spec:
  type: ClusterIP
  selector:
    app: product-service
    version: v1
  ports:
    - port: 8081
      targetPort: 8081